services:
  database:
    image: mysql:8.4
    container_name: mysql-database2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: orbit_root
      MYSQL_DATABASE: orbit
      MYSQL_USER: orbit
      MYSQL_PASSWORD: orbit_pw
    ports:
      - "3307:3306"
    volumes:
      - orbit_data:/var/lib/mysql
      - ./Db/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin2
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PMA_HOST: database
    ports:
      - "8081:80"

volumes:
  orbit_data: